
# Needs Makefile.pdlibbuilder as helper makefile for platform-dependent build
# settings and rules.

# library name
lib.name = jp_grainmaker

# make-lib-executeable = yes

# input source file (class name == source file basename)
class.sources = grainmaker~.c
grainmaker~.class.sources = grain_scheduler.c
grainmaker~.class.sources =	grain.c 

# lib.setup.sources = grainmaker~.c

# all extra files to be included in binary distribution of the library
datafiles =

# include Makefile.pdlibbuilder from submodule directory 'pd-lib-builder'
include Makefile.pdlibbuilder